# Generated by Django 3.1.6 on 2021-02-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profil_pic',
            new_name='profile_pic',
        ),
    ]
