# Generated by Django 3.1.6 on 2021-02-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210212_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_reset_password',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Token For Reset Password'),
        ),
    ]
