# Generated by Django 3.1.6 on 2021-02-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_token_reset_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token_reset_password',
            new_name='reset_token',
        ),
    ]
