# Generated by Django 3.1.6 on 2021-02-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210218_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='category',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Category Of Share'),
        ),
    ]
