# Generated by Django 3.1.6 on 2021-02-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_bookmark_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scope',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='category',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Category Id'),
        ),
    ]
