# Generated by Django 3.1.6 on 2021-02-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210219_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='scope',
        ),
    ]
